#
# This is a project Makefile. It is assumed the directory this Makefile resides in is a
# project subdirectory.
#
PROJECT_NAME := esp_aliyun_ir

EXTRA_COMPONENT_DIRS := components/ir_remote

include $(IDF_PATH)/make/project.mk